apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vjxra3zp3-dotnet-basic
  janus-idp.io/tekton: vjxra3zp3-dotnet-basic
  backstage.io/kubernetes-id: vjxra3zp3-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vjxra3zp3-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
